"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_1 = require("../controller/auth");
const middleware_1 = require("../middleware");
const routerAuth = (0, express_1.Router)();
routerAuth.post('/signup', auth_1.signup);
routerAuth.post('/signin', auth_1.signin);
routerAuth.get('/users', middleware_1.GetMid, auth_1.UsersGet);
routerAuth.get('/user', middleware_1.GetMid, auth_1.UserGet);
routerAuth.put('/user', auth_1.userPut);
exports.default = routerAuth;
